# NumPy 

#### Nessa aula vamos aprender um pouco sobre como trabalhar com a biblioteca [Numpy](https://numpy.org/). Um pacote para a linguagem Python que suporta arranjos e matrizes multidimensionais, contendo uma coleção de funções matemáticas para trabalhar com estas estruturas.

### Carregar e checar a versão de [`NumPy`](https://realpython.com/tutorials/numpy/).

#### Como o NumPy não é nativo do Python nós precisamos fazer uma importação da biblioteca. E para checar sua versão com a ajuda do atributo [`.__version__`](https://www.python.org/dev/peps/pep-0396/).

In [3]:
#s!pip install numpy
import numpy as np

#vamos verificar a versão instalada
np.__version__

'1.18.1'

#### O [`Numpy`](https://towardsdatascience.com/the-ultimate-beginners-guide-to-numpy-f5a2f99aef54#:~:text=NumPy%20can%20be%20used%20to,on%20these%20arrays%20and%20matrices.) é uma biblioteca com ferramentas para o trabalho com arranjos N-dimensionais. Vamos usar o método [`.arrange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html), que retorna valores com espaçamento uniforme em um determinado intervalo.

In [6]:
x = np.arange(10)
print(x)
#type(x)

[0 1 2 3 4 5 6 7 8 9]


### Começaremos exercitando as lista.

#### Será criada uma lista de $0$ à $1000000$ e em seguida uma segunda lista, cujos elementos  são o quadrado de cada elemento da primeira lista.

In [9]:
%%time

z = list(range(1000000))
z2 = []
for i in range(0, len(z)):
    z2.append(z[i] ** 2)

CPU times: user 586 ms, sys: 83.5 ms, total: 670 ms
Wall time: 1.16 s


#### Agora vamos ver como é a performance do array comparada com a lista. Observe que para isso usamos o [comando mágico](https://ipython.org/ipython-doc/3/interactive/magics.html) [`%%time`](https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-timeit).

In [10]:
%%time

y = np.arange(1000000)
y = y ** 2

CPU times: user 6.22 ms, sys: 7.75 ms, total: 14 ms
Wall time: 27.1 ms


#### A uma lista podemos adicionar vários tipos diferentes de variáveis. 

In [11]:
animal = ['Dog', 'Mammal', 45, 7]
print(animal)

['Dog', 'Mammal', 45, 7]


#### Com um [arranjo Numpy](https://towardsdatascience.com/numpy-array-all-you-want-to-know-d3f8503a2f8f) isso não acontece, todas as variáveis serão do mesmo tipo. 

In [12]:
np.array(animal)

array(['Dog', 'Mammal', '45', '7'], dtype='<U6')

#### Um [arranjo Numpy](https://machinelearningmastery.com/gentle-introduction-n-dimensional-arrays-python-numpy/) pode ter [quantas dimensões](https://numpy.org/doc/stable/reference/arrays.ndarray.html) desejarmos, porém é comum termos arranjos de $1$, $2$ e $3$ dimensões. Como será um arranjo de $3$ dimensões? O método [`.arrange()`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) retorna valores com espaçamento uniforme em um determinado intervalo e o método [`.reshape()`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) dá uma nova forma a uma matriz sem alterar seus dados.

In [14]:
ndim = np.arange(27).reshape(3, 3, 3)
print(ndim)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


#### Um array de quatro dimensões.

In [16]:
twos = np.arange(16).reshape(2, 2, 2, 2)
print(twos)

[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


#### Talvez você deseje utilizar um arranjo para salvar dados e precise fazer uma declaração de variável inicialmente para "guardar" memória para salvar futuros dados. Há algumas maneiras de se fazer isso, observe as os métodos:
- [`.ones()`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html), retorne uma nova matriz de forma e tipo fornecidos, preenchida com uns.
- [`.zeros()`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html), retorne uma nova matriz de forma e tipo fornecidos, preenchida com zeros.
- [`.eye()`](https://numpy.org/doc/stable/reference/generated/numpy.eye.html), retorne uma matriz 2-D com uns na diagonal e zeros em outros lugares.

In [21]:
#print(np.ones((3, 5)), end = '\n\n')
#print(np.zeros((3, 5)), end = '\n\n')
print(np.eye(3, 3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Como acessar dados dentro do arranjo? Vamos criar um arranjo de maneira randômica de tamanho $15$ com o método [`.randint()`](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.random.randint.html), que retorne inteiros aleatóriamente.

In [37]:
data = np.random.randint(low = 10, size = 15)
print(data)

[3 4 4 0 1 1 1 0 3 5 2 2 7 2 7]


#### Fazemos uma [slice](https://towardsdatascience.com/working-with-numpy-arrays-slicing-4453ec757ff0) dos dados.

In [38]:
data[4: 8]

array([1, 1, 1, 0])

#### E alteramos sua [forma](https://towardsdatascience.com/reshaping-numpy-arrays-in-python-a-step-by-step-pictorial-tutorial-aed5f471cf0b).

In [39]:
data = data.reshape(3, 5)
data

array([[3, 4, 4, 0, 1],
       [1, 1, 0, 3, 5],
       [2, 2, 7, 2, 7]])

In [50]:
#data[3,3]
data[:, 0: 1]

array([[3],
       [1],
       [2]])

####  <span style = "color:blue">Prática Independente.</span>

Coloque a lista seguinte e em ordem crescente:

1. lista_exercico = [8, 5, 2, 4, 9]

####  <span style = "color:red">Código original.</span>
<!--- 
x = np.array([8, 5, 2, 4, 9])
print(np.argsort(x))
#print(x[x.argsort()])
#print(x)
-->

#### o método [`.argsort()`](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html) retorna os índices que ordenariam uma arranjo.

In [55]:
x = np.array([8, 5, 2, 4, 9])
#type(x)
print(np.argsort(x))
print(x[x.argsort()])
#print(x)

[2 3 1 0 4]
[2 4 5 8 9]


#### Podemos usar o seqüênciamento de índices de um arranjo e um outro.

In [56]:
grade = np.array([3, 5, 1, 6, 2, 7])
ages = np.array([8, 10, 6, 11, 7, 12])

In [58]:
sort_index = np.argsort(ages)
sort_index

array([2, 4, 0, 1, 3, 5])

In [60]:
print(grade[sort_index])
print(ages[sort_index])

[1 2 3 5 6 7]
[ 6  7  8 10 11 12]


#### Em ordem decrescente. 

In [66]:
#print(ages[sort_index])
#print(list(ages[sort_index]))
print(list(ages[sort_index])[::-1])


[12, 11, 10, 8, 7, 6]


### Vamos manipular algum array

In [70]:
import numpy.random #as npr
#x = numpy.random.randint(-10, 10, size = 100)
x = npr.randint(-10, 10, size = 100)
print(x)

[ -6   0   1  -1   4   0   9  -5  -9  -3   3  -3   4  -9  -9  -5  -1   0
  -6   8  -5   3   7   7   8   4   5  -2   2  -5   5   9   7   7  -6   8
  -4  -8   0   3  -3   8   8  -3  -4   0  -6  -9   0   5 -10  -3  -6  -4
   6   4  -4   0   3   6  -1   1  -2   3  -6  -3   2   5  -6   2  -6   9
   8   9   6   9   0   9   8  -7   2   6   8  -4  -1  -5   3  -6 -10  -7
  -5   2  -9  -5  -5  -6  -1 -10   4  -9]


####  <span style = "color:blue">Prática independente.</span>

1. No array acima, substitua os valores menores que $-1$ por $-1$, e valores maiores que $5$ por $5$. Fazendo uso de [`for`].

#### Uma forma de fácil com uma única operação é fazer uso do método [`.clip()`](https://numpy.org/doc/stable/reference/generated/numpy.clip.html), que recorta as bordas de um dado intervalo, criando um subespaço.

In [78]:
#z = x.clip(-1, 5) 
#print(z)
print(x.clip(-1, 5))

[-1  0  1 -1  4  0  5 -1 -1 -1  3 -1  4 -1 -1 -1 -1  0 -1  5 -1  3  5  5
  5  4  5 -1  2 -1  5  5  5  5 -1  5 -1 -1  0  3 -1  5  5 -1 -1  0 -1 -1
  0  5 -1 -1 -1 -1  5  4 -1  0  3  5 -1  1 -1  3 -1 -1  2  5 -1  2 -1  5
  5  5  5  5  0  5  5 -1  2  5  5 -1 -1 -1  3 -1 -1 -1 -1  2 -1 -1 -1 -1
 -1 -1  4 -1]


In [79]:
print(x)

[ -6   0   1  -1   4   0   9  -5  -9  -3   3  -3   4  -9  -9  -5  -1   0
  -6   8  -5   3   7   7   8   4   5  -2   2  -5   5   9   7   7  -6   8
  -4  -8   0   3  -3   8   8  -3  -4   0  -6  -9   0   5 -10  -3  -6  -4
   6   4  -4   0   3   6  -1   1  -2   3  -6  -3   2   5  -6   2  -6   9
   8   9   6   9   0   9   8  -7   2   6   8  -4  -1  -5   3  -6 -10  -7
  -5   2  -9  -5  -5  -6  -1 -10   4  -9]


#### Suponha que você precisa realizar uma escolha aleatória de um número determindo de elementos de `x`, como podemos fazer isso? 

#### É possível aplicar o método [`.choice()`](https://docs.scipy.org/doc//numpy-1.10.4/reference/generated/numpy.random.choice.html), gera uma amostra aleatória de uma determinada matriz unidimensional.

In [84]:
y = npr.choice(x, 10, replace = False)
y

array([ 9,  4,  8,  3, -9, -5,  8, -4, -4,  5])

#### É possível, com a ajuda do parâmetro `p`, associar valores de probabilidades a cada entrada em `y` e realizar uma escolha não tão aleatória assim. Para o caso de `p` não ser fornecido, a amostra assume uma distribuição uniforme sobre todas as entradas em um. 

In [85]:
y = npr.choice(y, 10, p = [.05, .1, .15, .15, .05, .1, 0.15, .07, .08, 0.1])
y

array([-4,  8, -5, -4,  4, -4,  3, -4, -4,  9])

####  <span style = "color:blue">Prática independente.</span>

1. Encontre os elementos unicos do array a seguir.
2. O retorno deve ser o elemento e seu index.
3. A quantidade observada de cada elemento.

In [87]:
symbols = np.array(['BCD', 
                    'ACD', 
                    'ACD', 
                    'ACD', 
                    'ABD', 
                    'ABC', 
                    'ABC', 
                    'ABD', 
                    'ABD',
                    'BCD', 
                    'BCD', 
                    'ABC', 
                    'ABC', 
                    'BCD', 
                    'ACD']
                  )

#### O método [`.unique()`](https://numpy.org/doc/stable/reference/generated/numpy.unique.html), que encontra os elementos exclusivos de uma matriz e seus elementos exclusivos classificados.

- `return_index`, para casos `True`, retorna os índices do arranjo que resultam na matriz exclusiva.
- `return_counts`, para casos `True`, retorna o número de vezes que cada item exclusivo aparece em ar.

#### Existem três saídas opcionais, além dos elementos exclusivos:

In [94]:
a, b, c = np.unique(symbols, 
                    return_counts = True,
                    return_index = True                    
                   )

#### Os valores da matriz de entrada que fornecem os valores únicos.

In [95]:
a

array(['ABC', 'ABD', 'ACD', 'BCD'], dtype='<U3')

#### O número de vezes que cada valor único aparece na matriz de entrada.

In [96]:
c

array([4, 3, 4, 4])

#### A forma do arranjo `a` pode ser encontrada com o atributo [`.shape`](https://numpy.org/devdocs/reference/generated/numpy.shape.html), que retorna uma tupla com as dimensões do arranjos correspondente.

In [97]:
a.shape

(4,)

#### Os índices da matriz única que reconstrói a matriz de entrada.

In [98]:
b

array([5, 4, 1, 0])

#### Podemos operar com diferrentes arranjos e uma das formas é através da [`concatenação`](https://cmdlinetips.com/2018/04/how-to-concatenate-arrays-in-numpy/#:~:text=17%20%2C%2018%20%5D%5D) dos mesmos. A função [`.concatenate()`](https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html) une a uma sequência de matrizes ao longo de um eixo existente.

In [99]:
array_1 = [[1, 2],
           [3, 4]
          ]

array_2 = [[5, 6],
           [7, 8]
          ]


#[a00 a01]
#[a10 a11]

In [102]:
np.concatenate((array_1, 
                array_2), 
               axis = 0
              )

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### O parâmetro `axis` identifica o eixo ao longo do qual as matrizes serão unidas. Se o eixo for `NONE`, as matrizes serão [niveladas](https://www.w3resource.com/numpy/manipulation/ndarray-flatten.php#:~:text=ndarray.-,flatten()%20function,array%20collapsed%20into%20one%20dimension.&text='C'%20means%20to%20flatten%20in,(Fortran%2D%20style)%20order.) antes do uso. O padrão é $0$.

In [103]:
np.concatenate((array_1, 
                array_2)
               , axis = 1
              )

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### Um arranjo colapsado ([flatten Array](https://towardsdatascience.com/numpy-array-manipulation-5d2b42354688)) retorna uma cópia da matriz original.

In [105]:
arr = np.arange(27).reshape(3, 3, 3)
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

#### O método [`.flatten()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html) retorna uma cópia da matriz, colapsada em uma dimensão.

In [ ]:
arr.flatten()

#### O método [`.randit()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html) retorna inteiros aleatórios da distribuição “uniforme discreta” do tipo `d` especificado no intervalo “meio aberto” [baixo, alto). Se alto for Nenhum (o padrão), os resultados serão de [0, baixo).

In [107]:
x = npr.randint(-10, 10, size = 100)
x

array([ -6,   4,  -3,   5,   3,  -2,   2,   6,   5,   2,   4,  -2,   2,
        -1,   5,   2,   9,  -6,  -3,  -9,   3,   5,   5,   9,   6, -10,
        -5,  -9,  -6,  -2,   7,  -4, -10,   3,   7,   6,  -2,   8,  -1,
        -5,   7,   5,   3,   2,   4,   1,  -8,  -1,  -2,   2,   9,   7,
         7,   2,   0,  -2,  -4,  -1,   5,  -7,   8,   1,  -3,   0,   1,
        -8,   5,   8,   6,   3,   2,  -4,   4,  -9,   2,  -2,   9,  -2,
         5,   5,  -8,   8,  -4,  -9, -10,  -2,   6,  -8,  -9,   0,  -5,
       -10,  -3,   0,   3,  -7,   7,  -6,   0,  -2])

#### O método [`where()`](https://numpy.org/doc/stable/reference/generated/numpy.where.html) retorna elementos escolhidos de `x` ou `y` dependendo da condição.

In [114]:
positive = np.where(x > 0, 200, x)
print(positive)

[ -6 200  -3 200 200  -2 200 200 200 200 200  -2 200  -1 200 200 200  -6
  -3  -9 200 200 200 200 200 -10  -5  -9  -6  -2 200  -4 -10 200 200 200
  -2 200  -1  -5 200 200 200 200 200 200  -8  -1  -2 200 200 200 200 200
   0  -2  -4  -1 200  -7 200 200  -3   0 200  -8 200 200 200 200 200  -4
 200  -9 200  -2 200  -2 200 200  -8 200  -4  -9 -10  -2 200  -8  -9   0
  -5 -10  -3   0 200  -7 200  -6   0  -2]
